#!/usr/bin/env python3
"""
Visualize a mix generated by the GTO AutoDJ system.

Usage:
    python visualize_mix.py [path/to/mix_log.csv]

Generates mix_analysis.png in the current directory.
Reads mix_log.csv from the current directory by default.

Requires: matplotlib, numpy  (pip install matplotlib numpy)
"""

import sys
import csv
import numpy as np
import matplotlib
matplotlib.use('Agg')   # works without a display (Docker, SSH)
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from collections import Counter

# ---------------------------------------------------------------------------
# Camelot Wheel harmonic distance
# ---------------------------------------------------------------------------
CIRCLE = {
    'major': ['C', 'G', 'D', 'A', 'E', 'B', 'F#', 'C#', 'Ab', 'Eb', 'Bb', 'F'],
    'minor': ['A', 'E', 'B', 'F#', 'C#', 'Ab', 'Eb', 'Bb', 'F',  'C',  'G',  'D'],
}

def camelot_dist(k1, s1, k2, s2):
    try:
        i1 = CIRCLE[s1].index(k1)
        i2 = CIRCLE[s2].index(k2)
    except (ValueError, KeyError):
        return None
    return abs(((6 + ((i2 - i1) % 12)) % 12) - 6)

def shorten(title, n=18):
    return title[:n] + '…' if len(title) > n else title

# ---------------------------------------------------------------------------
# Color palettes
# ---------------------------------------------------------------------------
ACTION_COLORS  = {'START': '#888888', 'CALL': '#4C72B0',
                  'HOLD':  '#55A868', 'RAISE': '#C44E52', 'N/A': '#aaaaaa'}
CLUSTER_COLORS = {0: '#4C72B0', 1: '#DD8452', 2: '#C44E52'}
CLUSTER_LABELS = {0: 'Cluster 0 – low',  1: 'Cluster 1 – mid', 2: 'Cluster 2 – high'}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main(log_path):
    rows = []
    with open(log_path, newline='') as f:
        for row in csv.DictReader(f):
            rows.append(row)

    if not rows:
        print('mix_log.csv is empty – play a mix with "play save" first.')
        return

    steps    = [int(r['step'])           for r in rows]
    titles   = [r['title']               for r in rows]
    energies = [float(r['energy'])       for r in rows]
    planned  = [float(r['planned_energy']) for r in rows]
    clusters = [int(r['cluster'])        for r in rows]
    actions  = [r['action']              for r in rows]
    keys     = [r['key']                 for r in rows]
    scales   = [r['scale']               for r in rows]

    short = [shorten(t) for t in titles]

    camelot_dists = [
        camelot_dist(keys[i-1], scales[i-1], keys[i], scales[i])
        for i in range(1, len(rows))
    ]

    # -----------------------------------------------------------------------
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('GTO AutoDJ Mix Analysis', fontsize=15, fontweight='bold', y=1.01)

    # ---- 1. Energy Arc ------------------------------------------------
    ax = axes[0, 0]
    ax.plot(steps, planned, 'b--', linewidth=1.5, alpha=0.6, label='Planned sigmoid arc')
    ac = [ACTION_COLORS.get(a, '#888') for a in actions]
    ax.plot(steps, energies, '-', color='#333333', linewidth=1.5, zorder=2)
    ax.scatter(steps, energies, c=ac, s=80, zorder=3, edgecolors='white', linewidths=0.8)
    for x, y, t in zip(steps, energies, short):
        ax.annotate(t, (x, y), textcoords='offset points',
                    xytext=(0, 9), fontsize=7, ha='center', rotation=35)
    ax.set_xlabel('Track number')
    ax.set_ylabel('Energy  (−replaygain dB)')
    ax.set_title('Energy Arc: Planned vs Actual')
    ax.set_xticks(steps)
    ax.grid(True, alpha=0.25)
    # legend: planned line + action colours
    handles = [matplotlib.lines.Line2D([0], [0], color='b', linestyle='--', label='Planned arc')]
    handles += [mpatches.Patch(color=c, label=l)
                for l, c in ACTION_COLORS.items() if l != 'N/A']
    ax.legend(handles=handles, fontsize=7, loc='upper left')

    # ---- 2. GTO Action timeline --------------------------------------
    ax = axes[0, 1]
    bar_h = 0.55
    for i, (a, s) in enumerate(zip(actions, short)):
        color = ACTION_COLORS.get(a, '#888')
        ax.barh(i, 1, color=color, edgecolor='white', height=bar_h)
        ax.text(0.5, i, a, ha='center', va='center',
                fontsize=8, color='white', fontweight='bold')
    ax.set_yticks(range(len(steps)))
    ax.set_yticklabels(short, fontsize=8)
    ax.set_xlim(0, 1.1)
    ax.set_xticks([])
    ax.set_title('GTO Action per Track')
    ax.invert_yaxis()
    patches = [mpatches.Patch(color=c, label=l)
               for l, c in ACTION_COLORS.items() if l != 'N/A']
    ax.legend(handles=patches, fontsize=7, loc='lower right')

    # ---- 3. Harmonic (Camelot) compatibility -------------------------
    ax = axes[1, 0]
    pair_labels = [f'{shorten(titles[i], 10)}→{shorten(titles[i+1], 10)}'
                   for i in range(len(camelot_dists))]
    plot_dists  = [d if d is not None else 0 for d in camelot_dists]
    bar_colors  = ['#55A868' if (d is not None and d <= 1) else '#C44E52'
                   for d in camelot_dists]
    ax.bar(range(len(plot_dists)), plot_dists, color=bar_colors, edgecolor='white', width=0.6)
    ax.axhline(y=1, color='navy', linestyle='--', linewidth=1, label='Max compatible (1 step)')
    ax.set_xticks(range(len(pair_labels)))
    ax.set_xticklabels(pair_labels, rotation=40, ha='right', fontsize=7)
    ax.set_ylabel('Camelot distance')
    pct = 100 * sum(1 for d in camelot_dists if d is not None and d <= 1) / max(len(camelot_dists), 1)
    ax.set_title(f'Harmonic Compatibility  ({pct:.0f}% transitions ≤ 1 step)')
    ax.legend(fontsize=8)
    ax.grid(True, axis='y', alpha=0.25)
    ax.set_ylim(bottom=0)

    # ---- 4. Cluster sequence -----------------------------------------
    ax = axes[1, 1]
    cluster_c = [CLUSTER_COLORS.get(c, '#888') for c in clusters]
    ax.bar(range(len(steps)), clusters, color=cluster_c, edgecolor='white', width=0.6)
    ax.set_xticks(range(len(steps)))
    ax.set_xticklabels(short, rotation=40, ha='right', fontsize=7)
    ax.set_yticks([0, 1, 2])
    ax.set_yticklabels(['0  low', '1  mid', '2  high'])
    ax.set_ylabel('Energy cluster')
    ax.set_title('Cluster Sequence')
    ax.grid(True, axis='y', alpha=0.25)
    patches = [mpatches.Patch(color=CLUSTER_COLORS[k], label=CLUSTER_LABELS[k])
               for k in [0, 1, 2]]
    ax.legend(handles=patches, fontsize=7)

    # -----------------------------------------------------------------------
    plt.tight_layout()
    out = 'mix_analysis.png'
    plt.savefig(out, dpi=150, bbox_inches='tight')
    print(f'Saved → {out}')

    # Summary
    n = len(rows)
    comp = sum(1 for d in camelot_dists if d is not None and d <= 1)
    print(f'\nMix summary  ({n} tracks):')
    print(f'  Energy range : {min(energies):.2f} – {max(energies):.2f} dB  '
          f'(delta {max(energies)-min(energies):.2f} dB)')
    print(f'  Harmonic     : {comp}/{len(camelot_dists)} transitions compatible '
          f'({100*comp/max(len(camelot_dists),1):.0f}%)')
    print(f'  GTO actions  : {dict(Counter(actions[1:]))}')
    print(f'  Clusters     : {dict(Counter(clusters))}')


if __name__ == '__main__':
    path = sys.argv[1] if len(sys.argv) > 1 else './mix_log.csv'
    main(path)
